export const actions = Object.freeze({
  auth: 'auth',
  registration: 'registration',
  selected: 'selected',
  login: 'login',
  email: 'email',
  password: 'password',
  appIsReady: 'appIsReady',
  error: 'error',
  increment: 'increment',
  decrement: 'decrement',
  isKeyboardOpen: 'isKeyboardOpen',
  stateNames: {
    my: 'my',
    tutorial: 'tutorial',
    RegistrationScreen: 'Registration screen',
    LoginScreen: 'Login screen',
    count: 'count',
  },
});
